/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Clases;

import Conexiones.Conexion;
import Conexiones.Procedimientos;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdministraPlatillos extends javax.swing.JFrame {

    String Clasificacion,  IDP, Descripcion, Cla;
    
    public AdministraPlatillos() {
        initComponents();
        cargarPaquete();
        
    }
    
    private void cargarPaquete(){
        int i=0,columnas;
        DefaultTableModel modeloTabla = (DefaultTableModel) TblPlatos.getModel();
        modeloTabla.setRowCount(0);
        try{
            CallableStatement TEU = Conexion.getConexion().prepareCall("{call TODOS_PLATILLOS()}");
            ResultSet rs = TEU.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(i=0;i<columnas;i++){
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TxteID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtaDescripcion = new javax.swing.JTextArea();
        CboCla = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPlatos = new javax.swing.JTable();
        BtnAlta = new javax.swing.JButton();
        BtnBaja = new javax.swing.JButton();
        BtnCambio = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        jLabel1.setText("ADMINISTRAR PLATILLOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(251, 231, 228));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxteIDActionPerformed(evt);
            }
        });
        jPanel1.add(TxteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 170, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel2.setText("ID: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel3.setText("DESCRIPCIÓN:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel4.setText("CLASIFICACION:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        TxtaDescripcion.setColumns(20);
        TxtaDescripcion.setRows(5);
        jScrollPane2.setViewportView(TxtaDescripcion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 243, 69));

        CboCla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "Guarnicion", "Plato Fuerte-Aves", "Plato Fuerte-Carne", "Plato Fuerte-Pescado", "Postre", "Primer-Crema", "Primer-Sopa", "Segundo-Arroz", "Segundo-Ensalada", "Segundo-Pasta" }));
        jPanel1.add(CboCla, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 410, 228));

        TblPlatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TblPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Clasificacion", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblPlatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 220));

        BtnAlta.setText("ALTA");
        BtnAlta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAltaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 70, -1));

        BtnBaja.setText("BAJA");
        BtnBaja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBajaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 60, -1));

        BtnCambio.setText("CAMBIAR");
        BtnCambio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 100, -1));

        jButton4.setText("VOLVER");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 80, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondog.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 950, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxteIDActionPerformed
        Clasificacion=CboCla.getSelectedItem().toString();
    }//GEN-LAST:event_TxteIDActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        BienvenidaA BA = new BienvenidaA();
        BA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAltaActionPerformed
        switch(Clasificacion){
            case "Guarnicion":
                Cla="GUARN";
                break;
            case "Plato Fuerte-Aves":
                Cla="PFAVE";
                break;
            case "Plato Fuerte-Carne":
                Cla="PFCAR";
                break;
            case "Plato Fuerte-Pescado":
                Cla="PFPES";
                break;
            case "Postre":
                Cla="POSTR";
                break;
            case "Primer-Crema":
                Cla="PTCRE";
                break;
            case "Primer-Sopa":
                Cla="PTSOP";
                break;
            case "Segundo-Arroz":
                Cla="STARR";
                break;
            case "Segundo-Ensalada":
                Cla="STENS";
                break;
            case "Segundo-Pasta":
                Cla="STPST";
                break;
        }
        
        IDP=TxteID.getText();
        Descripcion=TxtaDescripcion.getText();
        
        try{
            Procedimientos.ALTA_PLATILLO(Cla, Descripcion);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarPaquete();
        
        JOptionPane.showMessageDialog(null, "Se ha dado de alta exitosamente");
    }//GEN-LAST:event_BtnAltaActionPerformed

    private void BtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBajaActionPerformed
        switch(Clasificacion){
            case "Guarnicion":
                Cla="GUARN";
                break;
            case "Plato Fuerte-Aves":
                Cla="PFAVE";
                break;
            case "Plato Fuerte-Carne":
                Cla="PFCAR";
                break;
            case "Plato Fuerte-Pescado":
                Cla="PFPES";
                break;
            case "Postre":
                Cla="POSTR";
                break;
            case "Primer-Crema":
                Cla="PTCRE";
                break;
            case "Primer-Sopa":
                Cla="PTSOP";
                break;
            case "Segundo-Arroz":
                Cla="STARR";
                break;
            case "Segundo-Ensalada":
                Cla="STENS";
                break;
            case "Segundo-Pasta":
                Cla="STPST";
                break;
        }
        
        IDP=TxteID.getText();
        Descripcion=TxtaDescripcion.getText();
        
        try{
            Procedimientos.BAJA_PLATILLO(IDP);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarPaquete();
        
        JOptionPane.showMessageDialog(null, "Se ha dado de baja exitosamente");
    }//GEN-LAST:event_BtnBajaActionPerformed

    private void BtnCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambioActionPerformed
        switch(Clasificacion){
            case "Guarnicion":
                Cla="GUARN";
                break;
            case "Plato Fuerte-Aves":
                Cla="PFAVE";
                break;
            case "Plato Fuerte-Carne":
                Cla="PFCAR";
                break;
            case "Plato Fuerte-Pescado":
                Cla="PFPES";
                break;
            case "Postre":
                Cla="POSTR";
                break;
            case "Primer-Crema":
                Cla="PTCRE";
                break;
            case "Primer-Sopa":
                Cla="PTSOP";
                break;
            case "Segundo-Arroz":
                Cla="STARR";
                break;
            case "Segundo-Ensalada":
                Cla="STENS";
                break;
            case "Segundo-Pasta":
                Cla="STPST";
                break;
        }
        
        IDP=TxteID.getText();
        Descripcion=TxtaDescripcion.getText();
        
        try{
            Procedimientos.CAMB_PLATILLO(IDP,Cla,Descripcion);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarPaquete();
        
        JOptionPane.showMessageDialog(null, "Se ha dado de baja exitosamente");
    }//GEN-LAST:event_BtnCambioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministraPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministraPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministraPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministraPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministraPlatillos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlta;
    private javax.swing.JButton BtnBaja;
    private javax.swing.JButton BtnCambio;
    private javax.swing.JComboBox<String> CboCla;
    private javax.swing.JTable TblPlatos;
    private javax.swing.JTextArea TxtaDescripcion;
    private javax.swing.JTextField TxteID;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
