/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Conexiones.Conexion;
import Conexiones.Procedimientos;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdministraPaquetes extends javax.swing.JFrame {

    String Nombre,  Precio, Horas,  Sillas,S, Max, Min, Tiempos;
    Integer Maximo, Minimo, T, H;
    Float p;
    public AdministraPaquetes() {
        initComponents();
        cargarPaquete();
        
    }
    
    private void cargarPaquete(){
        int i=0,columnas;
        DefaultTableModel modeloTabla = (DefaultTableModel) TblP.getModel();
        modeloTabla.setRowCount(0);
        try{
            CallableStatement TEU = Conexion.getConexion().prepareCall("{call TODOS_PAQUETES()}");
            ResultSet rs = TEU.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(i=0;i<columnas;i++){
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblP = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxteNombre = new javax.swing.JTextField();
        TxtePrecio = new javax.swing.JTextField();
        TxteCMax = new javax.swing.JTextField();
        TxteCMin = new javax.swing.JTextField();
        TxteHoras = new javax.swing.JTextField();
        TxteComidas = new javax.swing.JTextField();
        CboSillas = new javax.swing.JComboBox<>();
        BtnAlta = new javax.swing.JButton();
        BtnCambio = new javax.swing.JButton();
        BtnMenu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel8.setText("Administrar Paquetes");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 40));

        TblP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TblP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Precio P", "Capacidad Max.", "Capacidad Min.", "Horas Servicio", "Tiempos Comida", "Sillas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblP);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 560, 190));

        jPanel1.setBackground(new java.awt.Color(251, 231, 228));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 41, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel2.setText("Precio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 85, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel3.setText("Capacidad Max.:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 129, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel4.setText("Capacidad Min.:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 173, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel5.setText("Horas Servicio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 217, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel6.setText("Tiempos Comidas:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 261, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel7.setText("Sillas:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 305, -1, -1));
        jPanel1.add(TxteNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 39, 157, -1));
        jPanel1.add(TxtePrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 83, 157, -1));
        jPanel1.add(TxteCMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 127, 157, -1));
        jPanel1.add(TxteCMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 171, 157, -1));
        jPanel1.add(TxteHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 215, 157, -1));
        jPanel1.add(TxteComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 259, 157, -1));

        CboSillas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "Madera Plegable", "Metal Plegable", "Plastico Plegable", "Tiffany" }));
        CboSillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboSillasActionPerformed(evt);
            }
        });
        jPanel1.add(CboSillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 330, 350));

        BtnAlta.setText("Alta");
        BtnAlta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAltaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 70, -1));

        BtnCambio.setText("Cambiar");
        BtnCambio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 80, -1));

        BtnMenu.setText("Volver");
        BtnMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 90, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondog.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAltaActionPerformed
        Nombre=TxteNombre.getText();
        Max=TxteCMax.getText().toString();
        Min=TxteCMin.getText();
        Precio=TxtePrecio.getText();
        Horas=TxteHoras.getText();
        Tiempos=TxteComidas.getText();
        
        switch(Sillas){
            case "Madera Plegable":
                S="SIMAP";
                break;
            case "Metal Plegable":
                S="SIMEP";
                break;
            case "Plastico Plegable":
                S="SIPLP";
                break;
            case "Tiffany":
                S="SITIF";
                break;
        }
        
        Maximo=Integer.parseInt(Max);
        Minimo=Integer.parseInt(Min);
        T=Integer.parseInt(Tiempos);
        H=Integer.parseInt(Horas);
        p=Float.parseFloat(Precio);
        try{
            Procedimientos.ALTA_PAQUETE(Nombre, p,Maximo, Minimo, H, S, T);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarPaquete();
        
        JOptionPane.showMessageDialog(null, "Se ha dado de alta exitosamente");
        
    }//GEN-LAST:event_BtnAltaActionPerformed

    private void BtnCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambioActionPerformed
        Nombre=TxteNombre.getText();
        Max=TxteCMax.getText().toString();
        Min=TxteCMin.getText();
        Precio=TxtePrecio.getText();
        Horas=TxteHoras.getText();
        Tiempos=TxteComidas.getText();
        
        switch(Sillas){
            case "Madera Plegable":
                S="SIMAP";
                break;
            case "Metal Plegable":
                S="SIMEP";
                break;
            case "Plastico Plegable":
                S="SIPLP";
                break;
            case "Tiffany":
                S="SITIF";
                break;
        }
        
        Maximo=Integer.parseInt(Max);
        Minimo=Integer.parseInt(Min);
        T=Integer.parseInt(Tiempos);
        H=Integer.parseInt(Horas);
        
        
        try{
            Procedimientos.CAMB_PAQUETE(Nombre, Precio,Maximo, Minimo, H, S, T);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarPaquete();
        
        JOptionPane.showMessageDialog(null, "Se ha cambiado exitosamente");
    }//GEN-LAST:event_BtnCambioActionPerformed

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        BienvenidaA BA = new BienvenidaA();
        BA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnMenuActionPerformed

    private void CboSillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboSillasActionPerformed
        Sillas=CboSillas.getSelectedItem().toString();
    }//GEN-LAST:event_CboSillasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministraPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministraPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministraPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministraPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministraPaquetes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlta;
    private javax.swing.JButton BtnCambio;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JComboBox<String> CboSillas;
    private javax.swing.JTable TblP;
    private javax.swing.JTextField TxteCMax;
    private javax.swing.JTextField TxteCMin;
    private javax.swing.JTextField TxteComidas;
    private javax.swing.JTextField TxteHoras;
    private javax.swing.JTextField TxteNombre;
    private javax.swing.JTextField TxtePrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
