/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Conexiones.Conexion;
import Conexiones.Procedimientos;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp pavilion
 */
public class AdministraBebidas extends javax.swing.JFrame {

    String ID,NOMBRE,DESCRIPCION;
    Integer ALCOHOL;
    
    public AdministraBebidas() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblAdministraB = new javax.swing.JTable();
        BtnAlta = new javax.swing.JButton();
        BtnCamb = new javax.swing.JButton();
        BtnBaja = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TxtIDBebida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNmb = new javax.swing.JTextField();
        OptAlcohol = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtaDes = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblAdministraB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID BEBIDAS", "NOMBRE", "DESCRIPCION", "ALCHOL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblAdministraB);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 69, 375, 275));

        BtnAlta.setText("ALTA");
        BtnAlta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAltaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 70, -1));

        BtnCamb.setText("CAMBIO");
        BtnCamb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCamb, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 70, -1));

        BtnBaja.setText("BAJA");
        BtnBaja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBajaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 70, -1));

        BtnRegresar.setText("MENU");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel1.setText("Bebidas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(251, 231, 228));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtIDBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDBebidaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtIDBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, -1));

        jLabel2.setText("ID: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel3.setText("NOMBRE: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        jPanel1.add(TxtNmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 100, -1));

        OptAlcohol.setBackground(new java.awt.Color(255, 255, 255));
        OptAlcohol.setText("CON ALCHOL");
        jPanel1.add(OptAlcohol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel4.setText("DESCRIPCION:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        TxtaDes.setColumns(20);
        TxtaDes.setRows(5);
        jScrollPane2.setViewportView(TxtaDes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 267, 62));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 69, 497, 208));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondog.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 916, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAltaActionPerformed
        ID=TxtIDBebida.getText();
        NOMBRE=TxtNmb.getText();
        DESCRIPCION=TxtaDes.getText();
        if(OptAlcohol.isSelected()){
            ALCOHOL=1;
        }else{
            ALCOHOL=0;
        }
        
        try{
            Procedimientos.ALTA_BEBIDAS(NOMBRE, ALCOHOL, DESCRIPCION, ID);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarTabla();
        
        JOptionPane.showMessageDialog(null, "Se ha dado de alta exitosamente");
    }//GEN-LAST:event_BtnAltaActionPerformed

    private void BtnCambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambActionPerformed
        ID=TxtIDBebida.getText();
        NOMBRE=TxtNmb.getText();
        DESCRIPCION=TxtaDes.getText();
        if(OptAlcohol.isSelected()){
            ALCOHOL=0;
        }else{
            ALCOHOL=1;
        }
        
        try{
            Procedimientos.CAMB_BEBIDAS(NOMBRE, ALCOHOL, DESCRIPCION, ID);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarTabla();
        JOptionPane.showMessageDialog(null, "Se ha actualizado exitosamente");
    }//GEN-LAST:event_BtnCambActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBajaActionPerformed
        ID=TxtIDBebida.getText();
        NOMBRE=TxtNmb.getText();
        DESCRIPCION=TxtaDes.getText();
        if(OptAlcohol.isSelected()){
            ALCOHOL=0;
        }else{
            ALCOHOL=1;
        }
        
        try{
            Procedimientos.BAJA_BEBIDAS(ID);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarTabla();
        
        JOptionPane.showMessageDialog(null, "Se ha borrado exitosamente");
    }//GEN-LAST:event_BtnBajaActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        BienvenidaA BA = new BienvenidaA();
        BA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void TxtIDBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDBebidaActionPerformed

    private void cargarTabla(){
        int i=0,columnas;
        DefaultTableModel modeloTabla = (DefaultTableModel) TblAdministraB.getModel();
        modeloTabla.setRowCount(0);
        try{
            CallableStatement TEU = Conexion.getConexion().prepareCall("{call TODAS_BEBIDAS}");
            
            ResultSet rs = TEU.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(i=0;i<columnas;i++){
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministraBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministraBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministraBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministraBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministraBebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlta;
    private javax.swing.JButton BtnBaja;
    private javax.swing.JButton BtnCamb;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JRadioButton OptAlcohol;
    private javax.swing.JTable TblAdministraB;
    private javax.swing.JTextField TxtIDBebida;
    private javax.swing.JTextField TxtNmb;
    private javax.swing.JTextArea TxtaDes;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
