/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Conexiones.Conexion;
import Conexiones.Procedimientos;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp pavilion
 */
public class AdministraServicios extends javax.swing.JFrame {

    String ID, DESCRIPCION,DURACION, COSTO;
    float DUR, COS;
    public AdministraServicios() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TxtIDBebida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCosto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtaDescripcion = new javax.swing.JTextArea();
        SpnDuracion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblAdministraSe = new javax.swing.JTable();
        BtnAlta = new javax.swing.JButton();
        BtnCamb = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnBaja = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel1.setText("SErVICIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(251, 231, 228));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtIDBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDBebidaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtIDBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, -1));

        jLabel2.setText("ID: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel3.setText("DESCRIPCIÓN:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("DURACIÓN:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setText("COSTO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        TxtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCostoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 80, -1));

        TxtaDescripcion.setColumns(20);
        TxtaDescripcion.setRows(5);
        jScrollPane2.setViewportView(TxtaDescripcion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 243, 69));

        SpnDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpnDuracionActionPerformed(evt);
            }
        });
        jPanel1.add(SpnDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 69, 410, 228));

        TblAdministraSe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TblAdministraSe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID SERVICIO", "DESCRIPCION", "DURACION", "COSTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblAdministraSe);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 69, 375, 275));

        BtnAlta.setText("ALTA");
        BtnAlta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAltaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 80, -1));

        BtnCamb.setText("CAMBIO");
        BtnCamb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCamb, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 80, -1));

        jButton1.setText("MENU");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 70, -1));

        BtnBaja.setText("BAJA");
        BtnBaja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBajaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 80, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondog.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAltaActionPerformed
        ID=TxtIDBebida.getText();
        DESCRIPCION=TxtaDescripcion.getText();
        DURACION=SpnDuracion.getText();
        COSTO=TxtCosto.getText();
        
        DUR=Float.parseFloat(DURACION);
        COS=Float.parseFloat(COSTO);
        
        try{
            Procedimientos.ALTA_SERVICIOS(COS, DUR, DESCRIPCION, ID);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarTabla();
        
        JOptionPane.showMessageDialog(null, "Se ha dado de alta exitosamente");
    }//GEN-LAST:event_BtnAltaActionPerformed

    private void BtnCambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambActionPerformed
        ID=TxtIDBebida.getText();
        COSTO=TxtCosto.getText();
        COS=Float.parseFloat(COSTO);

        
        try{
            Procedimientos.CAMB_SERVICIOS(COS, ID);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarTabla();
        
        JOptionPane.showMessageDialog(null, "Se ha actualizado exitosamente");
    }//GEN-LAST:event_BtnCambActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BienvenidaA BA = new BienvenidaA();
        BA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCostoActionPerformed

    private void TxtIDBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDBebidaActionPerformed

    private void SpnDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpnDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpnDuracionActionPerformed

    private void BtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBajaActionPerformed
        ID=TxtIDBebida.getText();
        
        try{
            Procedimientos.BAJA_SERVICIOS(ID);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        cargarTabla();
        
        JOptionPane.showMessageDialog(null, "Se ha dado de baja exitosamente");
    }//GEN-LAST:event_BtnBajaActionPerformed
    private void cargarTabla(){
        int i=0,columnas;
        DefaultTableModel modeloTabla = (DefaultTableModel) TblAdministraSe.getModel();
        modeloTabla.setRowCount(0);
        try{
            CallableStatement TEU = Conexion.getConexion().prepareCall("{call TODOS_SERVICIOS}");
            
            ResultSet rs = TEU.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(i=0;i<columnas;i++){
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministraServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministraServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministraServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministraServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministraServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlta;
    private javax.swing.JButton BtnBaja;
    private javax.swing.JButton BtnCamb;
    private javax.swing.JTextField SpnDuracion;
    private javax.swing.JTable TblAdministraSe;
    private javax.swing.JTextField TxtCosto;
    private javax.swing.JTextField TxtIDBebida;
    private javax.swing.JTextArea TxtaDescripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
