/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Conexiones.Conexion;
import Conexiones.Procedimientos;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BebidasEventoU extends javax.swing.JFrame {

    String Bebida, idevento, idbebida, BajaBebida;
    
    public BebidasEventoU() {
        
        initComponents();
        idevento = Clases.EventosUsuario.IDEvento;
        TxtIDEvento.setText(idevento);
        
        try{
            Procedimientos.TODAS_BEBIDAS_EVENTO(idevento);
            
        }catch(SQLException e){
            
        }
        cargarTablaBebidaE(idevento);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtIDEvento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblBebidasE = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        BtnAgregar = new javax.swing.JButton();
        CboBebidas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CboBajaBebidas = new javax.swing.JComboBox<>();
        BtnBaja = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel1.setText("BEBIDAS DEL EVENTO: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 20));

        TxtIDEvento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(TxtIDEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 110, 30));

        TblBebidasE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TblBebidasE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Bebida", "Nombre", "Descripcion", "Alcoholica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblBebidasE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 700, 220));

        jPanel2.setBackground(new java.awt.Color(251, 231, 228));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnAgregar.setText("Agregar");
        BtnAgregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        CboBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua de Jamaica", "Horchata de Arroz", "Horchata de Avena", "Horchata de Coco", "Horchata de Nuez", "Agua de Tamarindo", "Mezcal", "Tequila", "Té de Sobres", "Vodka Absolute", "Vodka SKY", "Smirnoff " }));
        CboBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboBebidasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel2.setText("Agregar Bebidas:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CboBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregar)
                    .addComponent(CboBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 350, 110));

        jPanel3.setBackground(new java.awt.Color(251, 231, 228));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel3.setText("Eliminar Bebidas:");

        CboBajaBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua de Jamaica", "Horchata de Arroz", "Horchata de Avena", "Horchata de Coco", "Horchata de Nuez", "Agua de Tamarindo", "Mezcal", "Tequila", "Té de Sobres", "Vodka Absolute", "Vodka SKY", "Smirnoff " }));
        CboBajaBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboBajaBebidasActionPerformed(evt);
            }
        });

        BtnBaja.setText("Baja");
        BtnBaja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CboBajaBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(BtnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboBajaBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBaja))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 350, 110));

        jButton1.setText("Volver");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 90, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondog.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 880, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboBebidasActionPerformed
        Bebida=CboBebidas.getSelectedItem().toString();
    }//GEN-LAST:event_CboBebidasActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        switch(Bebida){
            case "Agua de Jamaica":
                idbebida="AJAMA";
                break;
            case "Horchata de Arroz":
                idbebida="AORAR";
                break;
            case "Horchata de Avena":
                idbebida="AORAV";
                break;
            case "Horchata de Coco":
                idbebida="AORCC";
                break;
            case "Horchata de Nuez":
                idbebida="AORNZ";
                break;
            case "Agua de Tamarindo":
                idbebida="ATAMA";
                break;
            case "Mezcal":
                idbebida="MZNAT";
                break;
            case "Tequila":
                idbebida="TE1CV";
                break;
            case "Té de Sobres":
                idbebida="TESBR";
                break;
            case "Vodka Absolute":
                idbebida="VKABS";
                break;
            case "Vodka SKY":
                idbebida="VKSKY";
                break;
            case "Smirnoff ":
                idbebida="VKSMF";
                break;
        }

        try{
            Procedimientos.ALTA_EVENTOBEBIDAS(idevento, idbebida);
        }catch(SQLException e){
            
        }
        
        this.setVisible(false);
        this.setVisible(true);
        cargarTablaBebidaE(idevento);
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void CboBajaBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboBajaBebidasActionPerformed
        BajaBebida=CboBajaBebidas.getSelectedItem().toString();
    }//GEN-LAST:event_CboBajaBebidasActionPerformed

    private void BtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBajaActionPerformed
        switch(BajaBebida){
            case "Agua de Jamaica":
                idbebida="AJAMA";
                break;
            case "Horchata de Arroz":
                idbebida="AORAR";
                break;
            case "Horchata de Avena":
                idbebida="AORAV";
                break;
            case "Horchata de Coco":
                idbebida="AORCC";
                break;
            case "Horchata de Nuez":
                idbebida="AORNZ";
                break;
            case "Agua de Tamarindo":
                idbebida="ATAMA";
                break;
            case "Mezcal":
                idbebida="MZNAT";
                break;
            case "Tequila":
                idbebida="TE1CV";
                break;
            case "Té de Sobres":
                idbebida="TESBR";
                break;
            case "Vodka Absolute":
                idbebida="VKABS";
                break;
            case "Vodka SKY":
                idbebida="VKSKY";
                break;
            case "Smirnoff ":
                idbebida="VKSMF";
                break;
        }

        try{
            Procedimientos.BAJA_EVENTOBEBIDAS(idevento, idbebida);
        }catch(SQLException e){
            
        }
        
        this.setVisible(false);
        this.setVisible(true);
        cargarTablaBebidaE(idevento);
    }//GEN-LAST:event_BtnBajaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DetallesEventoUID EU = new DetallesEventoUID();
        EU.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cargarTablaBebidaE(String IDEVENTO){
        int i=0,columnas;
        DefaultTableModel modeloTabla = (DefaultTableModel) TblBebidasE.getModel();
        modeloTabla.setRowCount(0);
        try{
            CallableStatement TEU = Conexion.getConexion().prepareCall("{call TODAS_BEBIDAS_EVENTO(?)}");
            TEU.setString(1, IDEVENTO);
            ResultSet rs = TEU.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(i=0;i<columnas;i++){
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BebidasEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BebidasEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BebidasEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BebidasEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BebidasEventoU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnBaja;
    private javax.swing.JComboBox<String> CboBajaBebidas;
    private javax.swing.JComboBox<String> CboBebidas;
    private javax.swing.JTable TblBebidasE;
    private javax.swing.JLabel TxtIDEvento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
