/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

/**
 *
 * @author Finanzas_CDMX
 */
public class BienvenidaU extends javax.swing.JFrame {

    /**
     * Creates new form BienvenidaU
     */
    public BienvenidaU() {
        initComponents();
        TxtUsuario.setText(Logueo.Usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnVerE = new javax.swing.JButton();
        BtnCrearE = new javax.swing.JButton();
        BtnModificarP = new javax.swing.JButton();
        BtnVerP = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        jLabel1.setText("¡Bienvenido!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        TxtUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TxtUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 147, 48));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("A continuación tienes las siguientes opciones...");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        BtnVerE.setText("Ver Eventos ");
        BtnVerE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnVerE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerEActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVerE, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 120, -1));

        BtnCrearE.setText("Crear Evento");
        BtnCrearE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCrearE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearEActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCrearE, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 120, -1));

        BtnModificarP.setText("Modificar Perfil");
        BtnModificarP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnModificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarPActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 130, -1));

        BtnVerP.setText("Ver Perfil");
        BtnVerP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnVerP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerPActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVerP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 130, -1));

        jButton1.setText("Salir");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 70, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondog.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarPActionPerformed
        ModificarPerfil PE = new ModificarPerfil();
        PE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnModificarPActionPerformed

    private void BtnVerEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerEActionPerformed
        EventosUsuario EU =new EventosUsuario();
        EU.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVerEActionPerformed

    private void BtnVerPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerPActionPerformed
        PerfilU PU =new PerfilU();
        PU.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVerPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnCrearEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearEActionPerformed
        CrearEventoU CEU =new CrearEventoU();
        CEU.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnCrearEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BienvenidaU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BienvenidaU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BienvenidaU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BienvenidaU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BienvenidaU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearE;
    private javax.swing.JButton BtnModificarP;
    private javax.swing.JButton BtnVerE;
    private javax.swing.JButton BtnVerP;
    private javax.swing.JLabel TxtUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
