/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Clases;

import Conexiones.Procedimientos;
import java.sql.SQLException;

public class CrearEventoU extends javax.swing.JFrame {
    
    String IDUSUARIO, TIPO, INICIO, FINAL, FECHA, PERSONAS, PLALIST, MANTEL, MONTAJE, PAQUETE;
    String STIPO, SINICIO, SFINAL, SMANTEL, SMONTAJE, SPAQUETE;
    
    public CrearEventoU() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxteFecha = new javax.swing.JTextField();
        TxtePersonas = new javax.swing.JTextField();
        CboInicio = new javax.swing.JComboBox<>();
        CboFin = new javax.swing.JComboBox<>();
        CboMantel = new javax.swing.JComboBox<>();
        CboMontaje = new javax.swing.JComboBox<>();
        CboPaquete = new javax.swing.JComboBox<>();
        BtnManteles = new javax.swing.JButton();
        BtnMontajes = new javax.swing.JButton();
        BtnPaquetes = new javax.swing.JButton();
        BtnCrear = new javax.swing.JButton();
        CboTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TxtePlaylist = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel1.setText("DAR ALTA EVENTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel2.setText("TIPO EVENTO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel3.setText("HORA INICIO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel4.setText("HORA FIN:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel5.setText("FECHA:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel6.setText("NUM. PERSONAS:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel8.setText("MANTELERIA:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel9.setText("MONTAJES:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel10.setText("PAQUETE:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        TxteFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxteFechaActionPerformed(evt);
            }
        });
        getContentPane().add(TxteFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 130, -1));
        getContentPane().add(TxtePersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 130, -1));

        CboInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00:00", "13:00:00", "14:00:00", "15:00:00", "16:00:00", "17:00:00", "18:00:00", "19:00:00", "20:00:00", "21:00:00", "22:00:00" }));
        CboInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboInicioActionPerformed(evt);
            }
        });
        getContentPane().add(CboInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        CboFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20:00:00", "21:00:00", "22:00:00", "23:00:00", "24:00:00", "01:00:00", "02:00:00", "03:00:00", "04:00:00", "05:00:00" }));
        CboFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboFinActionPerformed(evt);
            }
        });
        getContentPane().add(CboFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        CboMantel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Satín", "Organza", "Plastico", "Razo" }));
        CboMantel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboMantelActionPerformed(evt);
            }
        });
        getContentPane().add(CboMantel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        CboMontaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escuela", "Auditorio", "Espiga", "Herradura", "Media Luna", "Imperial", "Mesa Rusa", "Banquete", "Cocktel" }));
        CboMontaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboMontajeActionPerformed(evt);
            }
        });
        getContentPane().add(CboMontaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        CboPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atenea", "Artemisa", "Hefesto", "Hermes", "Hera", "Afrodita", "Dionisio", "Apolo" }));
        CboPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboPaqueteActionPerformed(evt);
            }
        });
        getContentPane().add(CboPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        BtnManteles.setText("Mostrar Manteleria");
        BtnManteles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnManteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMantelesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnManteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 150, -1));

        BtnMontajes.setText("Mostrar Montaje");
        BtnMontajes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMontajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMontajesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMontajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 150, -1));

        BtnPaquetes.setText("Mostrar Paquetes");
        BtnPaquetes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPaquetesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPaquetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 150, -1));

        BtnCrear.setText("Crear Evento");
        BtnCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 130, -1));

        CboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduacion", "Boda", "XV", "Escolar/Congreso" }));
        CboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboTipoActionPerformed(evt);
            }
        });
        getContentPane().add(CboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel7.setText("PLAYLIST");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));
        getContentPane().add(TxtePlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 280, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondog.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxteFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxteFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxteFechaActionPerformed

    private void CboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboTipoActionPerformed
        STIPO=CboTipo.getSelectedItem().toString();
    }//GEN-LAST:event_CboTipoActionPerformed

    private void CboInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboInicioActionPerformed
        SINICIO=CboInicio.getSelectedItem().toString();
    }//GEN-LAST:event_CboInicioActionPerformed

    private void CboFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboFinActionPerformed
        SFINAL=CboFin.getSelectedItem().toString();
    }//GEN-LAST:event_CboFinActionPerformed

    private void CboMantelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboMantelActionPerformed
        SMANTEL=CboMantel.getSelectedItem().toString();
    }//GEN-LAST:event_CboMantelActionPerformed

    private void CboMontajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboMontajeActionPerformed
        SMONTAJE=CboMontaje.getSelectedItem().toString();
    }//GEN-LAST:event_CboMontajeActionPerformed

    private void CboPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboPaqueteActionPerformed
        SPAQUETE=CboPaquete.getSelectedItem().toString();
    }//GEN-LAST:event_CboPaqueteActionPerformed

    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
        switch(STIPO){
            case "Graduacion":
                TIPO="GRADUACION";
                break;
            case "Boda":
                TIPO="BODA";
                break;
            case "XV":
                TIPO="XV";
                break;
            case "Escolar/Congreso":
                TIPO="ESCOLAR/CONGRESO";
                break;
        }
        
        INICIO=SINICIO;
        FINAL=SFINAL;
        FECHA=TxteFecha.getText();
        PERSONAS=TxtePersonas.getText();
        PLALIST=TxtePlaylist.getText();
        switch(SMANTEL){
            case "Satín":
                MANTEL="0001";
                break;
            case "Organza":
                MANTEL="0003";
                break;
            case "Plastico":
                MANTEL="0004";
                break;
            case "Razo":
                MANTEL="0013";
                break;
        }
        
        switch(SMONTAJE){
            case "Escuela":
                MONTAJE="001";
                break;
            case "Auditorio":
                MONTAJE="003";
                break;
            case "Espiga":
                MONTAJE="005";
                break;
            case "Herradura":
                MONTAJE="004";
                break;
            case "Media Luna":
                MONTAJE="007";
                break;
            case "Imperial":
                MONTAJE="008";
                break;
            case "Mesa Rusa":
                MONTAJE="006";
                break;
            case "Banquete":
                MONTAJE="009";
                break;
            case "Cocktel":
                MONTAJE="002";
                break;
        }
        
        PAQUETE=SPAQUETE;
        
        IDUSUARIO=Logueo.IDUsuario;
        
        try{
            Procedimientos.ALTA_EVENTO(TIPO, INICIO, FINAL, FECHA, PERSONAS, PLALIST, MANTEL, MONTAJE, PAQUETE, IDUSUARIO);
        }catch(SQLException e){
            
        }
        
        EventosUsuario EU = new EventosUsuario();
        EU.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BtnCrearActionPerformed

    private void BtnMantelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMantelesActionPerformed
        
        VerManteles VM = new VerManteles();
        VM.setVisible(true);
    }//GEN-LAST:event_BtnMantelesActionPerformed

    private void BtnMontajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMontajesActionPerformed
        VerMontaje VJ =new VerMontaje();
        VJ.setVisible(true);
    }//GEN-LAST:event_BtnMontajesActionPerformed

    private void BtnPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPaquetesActionPerformed
        VerPaquete VP = new VerPaquete();
        VP.setVisible(true);
    }//GEN-LAST:event_BtnPaquetesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEventoU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnManteles;
    private javax.swing.JButton BtnMontajes;
    private javax.swing.JButton BtnPaquetes;
    private javax.swing.JComboBox<String> CboFin;
    private javax.swing.JComboBox<String> CboInicio;
    private javax.swing.JComboBox<String> CboMantel;
    private javax.swing.JComboBox<String> CboMontaje;
    private javax.swing.JComboBox<String> CboPaquete;
    private javax.swing.JComboBox<String> CboTipo;
    private javax.swing.JTextField TxteFecha;
    private javax.swing.JTextField TxtePersonas;
    private javax.swing.JTextField TxtePlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
