/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Conexiones.Conexion;
import Conexiones.Procedimientos;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuEventoU extends javax.swing.JFrame {

    String idevento, altamenu, bajamenu, idplatillo;
    
    public MenuEventoU() {
        initComponents();
        
        idevento = Clases.EventosUsuario.IDEvento;
        TxtEvento.setText(idevento);
        
        cargarTabla(idevento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegresar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CboEliminar = new javax.swing.JComboBox<>();
        BtnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CboAgregar = new javax.swing.JComboBox<>();
        BtnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblMenu = new javax.swing.JTable();
        TxtEvento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegresar.setText("Volver");
        BtnRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 120, -1));

        jPanel3.setBackground(new java.awt.Color(251, 231, 228));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Elminar del Menu");

        CboEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caldo Poblano", "Sopa de Cebolla", "Sopa de Tortilla", "Sopa Roquefort", "Sopa de Mariscos", "Crema de Nuez", "Crema de Ostiones", "Crema de Tomate", "Crema Poblana", "Crema de Elote", "Crema de 3 Quesos", "Ensalada Cesar", "Ensalada Campestre", "Ensalada de Jitomate", "Ensalada Fresca", "Ensalada de Papas", "Canelones Napoitana", "Fettucine al Epazote", "Fideo a la Mexicana", "Spaguetti Rojo", "Spaguetti con Jamon y Crema", "Arroz al Curry", "Arroz Blanco", "Arroz Rojo", "Arroz al Chino", "Paella", "Mole Poblano", "Pollo con Crema de Champiñones", "Pechugas Cordoblue", "Pollo Endiablado", "Pechugas Italianas", "Pescado Empapelado", "Camarones al Ajillo", "Bacalao a la Vizcana", "Coctel de Mariscos", "Pescado Provenzal", "Lomo de Puerco Adobado", "Mole de Olla", "Pierna de Puerco en Salsa de Tamarindo", "Chiles en Nogada", "Chop Suey", "Souffle de Papa", "Espinacas al Gratin", "Papas al Horno", "Nopales en Escabeche", "Ensalada Rusa", "Verduras al Vapor", "Arroz con Leche", "Natilla", "Mousse de Mango", "Flan de Nuez", "Nieve de CocaCola y Bombones" }));
        CboEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboEliminarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CboEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEliminar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 494, -1));

        jPanel2.setBackground(new java.awt.Color(251, 231, 228));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Agregar al Menu");

        CboAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caldo Poblano", "Sopa de Cebolla", "Sopa de Tortilla", "Sopa Roquefort", "Sopa de Mariscos", "Crema de Nuez", "Crema de Ostiones", "Crema de Tomate", "Crema Poblana", "Crema de Elote", "Crema de 3 Quesos", "Ensalada Cesar", "Ensalada Campestre", "Ensalada de Jitomate", "Ensalada Fresca", "Ensalada de Papas", "Canelones Napoitana", "Fettucine al Epazote", "Fideo a la Mexicana", "Spaguetti Rojo", "Spaguetti con Jamon y Crema", "Arroz al Curry", "Arroz Blanco", "Arroz Rojo", "Arroz al Chino", "Paella", "Mole Poblano", "Pollo con Crema de Champiñones", "Pechugas Cordoblue", "Pollo Endiablado", "Pechugas Italianas", "Pescado Empapelado", "Camarones al Ajillo", "Bacalao a la Vizcana", "Coctel de Mariscos", "Pescado Provenzal", "Lomo de Puerco Adobado", "Mole de Olla", "Pierna de Puerco en Salsa de Tamarindo", "Chiles en Nogada", "Chop Suey", "Souffle de Papa", "Espinacas al Gratin", "Papas al Horno", "Nopales en Escabeche", "Ensalada Rusa", "Verduras al Vapor", "Arroz con Leche", "Natilla", "Mousse de Mango", "Flan de Nuez", "Nieve de CocaCola y Bombones" }));
        CboAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboAgregarActionPerformed(evt);
            }
        });

        BtnAgregar.setText("Agregar");
        BtnAgregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CboAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        TblMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Menu", "Descripcion", "Tiempo", "SubTipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblMenu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1070, 191));

        TxtEvento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(TxtEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 187, 29));

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel1.setText("MENU DEL EVENTO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondog.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1140, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboEliminarActionPerformed
        bajamenu=CboEliminar.getSelectedItem().toString();
    }//GEN-LAST:event_CboEliminarActionPerformed

    private void CboAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboAgregarActionPerformed
        altamenu=CboAgregar.getSelectedItem().toString();
    }//GEN-LAST:event_CboAgregarActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        switch(altamenu){
            case "Caldo Poblano":
                idplatillo="1SOP001";
                break;
            case "Sopa de Cebolla":
                idplatillo="1SOP002";
                break;
            case "Sopa de Tortilla":
                idplatillo="1SOP003";
                break;
            case "Sopa Roquefort":
                idplatillo="1SOP004";
                break;
            case "Sopa de Mariscos":
                idplatillo="1SOP005";
                break;
            case "Crema de Nuez":
                idplatillo="1CRE001";
                break;
            case "Crema de Ostiones":
                idplatillo="1CRE002";
                break;
            case "Crema de Tomate":
                idplatillo="1CRE003";
                break;
            case "Crema Poblana":
                idplatillo="1CRE004";
                break;
            case "Crema de Elote":
                idplatillo="1CRE005";
                break;
            case "Crema de 3 Quesos":
                idplatillo="2CRE006";
                break;
            case "Ensalada Cesar":
                idplatillo="2ENS001";
                break;
            case "Ensalada Campestre":
                idplatillo="2ENS002";
                break;
            case "Ensalada de Jitomate":
                idplatillo="2ENS003";
                break;
            case "Ensalada Fresca":
                idplatillo="2ENS004";
                break;
            case "Ensalada de Papas":
                idplatillo="2ENS005";
                break;
            case "Canelones Napoitana":
                idplatillo="2PST001";
                break;
            case "Fettucine al Epazote":
                idplatillo="2PST002";
                break;
            case "Fideo a la Mexicana":
                idplatillo="2PST003";
                break;
            case "Spaguetti Rojo":
                idplatillo="2PST004";
                break;
            case "Spaguetti con Jamon y Crema":
                idplatillo="2PST005";
                break;
            case "Arroz al Curry":
                idplatillo="2ARR001";
                break;
            case "Arroz Blanco":
                idplatillo="2ARR002";
                break;
            case "Arroz Rojo":
                idplatillo="2ARR003";
                break;
            case "Arroz al Chino":
                idplatillo="2ARR004";
                break;
            case "Paella":
                idplatillo="2ARR005";
                break;
            case "Mole Poblano":
                idplatillo="3AVE001";
                break;
            case "Pollo con Crema de Champiñones":
                idplatillo="3AVE002";
                break;
            case "Pechugas Cordoblue":
                idplatillo="3AVE003";
                break;
            case "Pollo Endiablado":
                idplatillo="3AVE004";
                break;
            case "Pechugas Italianas":
                idplatillo="3AVE005";
                break;
            case "Pescado Empapelado":
                idplatillo="3PES001";
                break;
            case "Camarones al Ajillo":
                idplatillo="3PES002";
                break;
            case "Bacalao a la Vizcana":
                idplatillo="3PES003";
                break;
            case "Coctel de Mariscos":
                idplatillo="3PES004";
                break;
            case "Pescado Provenzal":
                idplatillo="3PES005";
                break;
            case "Lomo de Puerco Adobado":
                idplatillo="3CAR001";
                break;
            case "Mole de Olla":
                idplatillo="3CAR002";
                break;
            case "Pierna de Puerco en Salsa de Tamarindo":
                idplatillo="3CAR003";
                break;
            case "Chiles en Nogada":
                idplatillo="3CAR004";
                break;
            case "Chop Suey":
                idplatillo="3CAR005";
                break;
            case "Souffle de Papa":
                idplatillo="3GAR001";
                break;
            case "Espinacas al Gratin":
                idplatillo="3GAR002";
                break;
            case "Papas al Horno":
                idplatillo="3GAR003";
                break;
            case "Nopales en Escabeche":
                idplatillo="3GAR004";
                break;
            case "Ensalada Rusa":
                idplatillo="3GAR005";
                break;
            case "Verduras al Vapor":
                idplatillo="3GAR006";
                break;
            case "Arroz con Leche":
                idplatillo="4POS001";
                break;
            case "Natilla":
                idplatillo="4POS002";
                break;
            case "Mousse de Mango":
                idplatillo="4POS003";
                break;
            case "Flan de Nuez":
                idplatillo="4POS004";
                break;
            case "Nieve de CocaCola y Bombones":
                idplatillo="4POS005";
                break;
        }
        
        
        
	
        try{
            Procedimientos.ALTA_CAMB_MENU(idevento, idplatillo);
        }catch(SQLException e){
            
        }
        
        this.setVisible(false);
        this.setVisible(true);
        cargarTabla(idevento);
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        switch(bajamenu){
            case "Caldo Poblano":
                idplatillo="1SOP001";
                break;
            case "Sopa de Cebolla":
                idplatillo="1SOP002";
                break;
            case "Sopa de Tortilla":
                idplatillo="1SOP003";
                break;
            case "Sopa Roquefort":
                idplatillo="1SOP004";
                break;
            case "Sopa de Mariscos":
                idplatillo="1SOP005";
                break;
            case "Crema de Nuez":
                idplatillo="1CRE001";
                break;
            case "Crema de Ostiones":
                idplatillo="1CRE002";
                break;
            case "Crema de Tomate":
                idplatillo="1CRE003";
                break;
            case "Crema Poblana":
                idplatillo="1CRE004";
                break;
            case "Crema de Elote":
                idplatillo="1CRE005";
                break;
            case "Crema de 3 Quesos":
                idplatillo="2CRE006";
                break;
            case "Ensalada Cesar":
                idplatillo="2ENS001";
                break;
            case "Ensalada Campestre":
                idplatillo="2ENS002";
                break;
            case "Ensalada de Jitomate":
                idplatillo="2ENS003";
                break;
            case "Ensalada Fresca":
                idplatillo="2ENS004";
                break;
            case "Ensalada de Papas":
                idplatillo="2ENS005";
                break;
            case "Canelones Napoitana":
                idplatillo="2PST001";
                break;
            case "Fettucine al Epazote":
                idplatillo="2PST002";
                break;
            case "Fideo a la Mexicana":
                idplatillo="2PST003";
                break;
            case "Spaguetti Rojo":
                idplatillo="2PST004";
                break;
            case "Spaguetti con Jamon y Crema":
                idplatillo="2PST005";
                break;
            case "Arroz al Curry":
                idplatillo="2ARR001";
                break;
            case "Arroz Blanco":
                idplatillo="2ARR002";
                break;
            case "Arroz Rojo":
                idplatillo="2ARR003";
                break;
            case "Arroz al Chino":
                idplatillo="2ARR004";
                break;
            case "Paella":
                idplatillo="2ARR005";
                break;
            case "Mole Poblano":
                idplatillo="3AVE001";
                break;
            case "Pollo con Crema de Champiñones":
                idplatillo="3AVE002";
                break;
            case "Pechugas Cordoblue":
                idplatillo="3AVE003";
                break;
            case "Pollo Endiablado":
                idplatillo="3AVE004";
                break;
            case "Pechugas Italianas":
                idplatillo="3AVE005";
                break;
            case "Pescado Empapelado":
                idplatillo="3PES001";
                break;
            case "Camarones al Ajillo":
                idplatillo="3PES002";
                break;
            case "Bacalao a la Vizcana":
                idplatillo="3PES003";
                break;
            case "Coctel de Mariscos":
                idplatillo="3PES004";
                break;
            case "Pescado Provenzal":
                idplatillo="3PES005";
                break;
            case "Lomo de Puerco Adobado":
                idplatillo="3CAR001";
                break;
            case "Mole de Olla":
                idplatillo="3CAR002";
                break;
            case "Pierna de Puerco en Salsa de Tamarindo":
                idplatillo="3CAR003";
                break;
            case "Chiles en Nogada":
                idplatillo="3CAR004";
                break;
            case "Chop Suey":
                idplatillo="3CAR005";
                break;
            case "Souffle de Papa":
                idplatillo="3GAR001";
                break;
            case "Espinacas al Gratin":
                idplatillo="3GAR002";
                break;
            case "Papas al Horno":
                idplatillo="3GAR003";
                break;
            case "Nopales en Escabeche":
                idplatillo="3GAR004";
                break;
            case "Ensalada Rusa":
                idplatillo="3GAR005";
                break;
            case "Verduras al Vapor":
                idplatillo="3GAR006";
                break;
            case "Arroz con Leche":
                idplatillo="4POS001";
                break;
            case "Natilla":
                idplatillo="4POS002";
                break;
            case "Mousse de Mango":
                idplatillo="4POS003";
                break;
            case "Flan de Nuez":
                idplatillo="4POS004";
                break;
            case "Nieve de CocaCola y Bombones":
                idplatillo="4POS005";
                break;
        }
        
        
        
	
        try{
            Procedimientos.BAJA_MENU(idevento, idplatillo);
        }catch(SQLException e){
            
        }
        
        this.setVisible(false);
        this.setVisible(true);
        cargarTabla(idevento);
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        DetallesEventoUID EU = new DetallesEventoUID();
        EU.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void cargarTabla(String IDEVENTO){
        int i=0,columnas;
        DefaultTableModel modeloTabla = (DefaultTableModel) TblMenu.getModel();
        modeloTabla.setRowCount(0);
        try{
            CallableStatement TEU = Conexion.getConexion().prepareCall("{call MENU_IDEVENTO(?)}");
            TEU.setString(1, IDEVENTO);
            ResultSet rs = TEU.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(i=0;i<columnas;i++){
                    fila[i] = rs.getObject(i+1);
                }
                modeloTabla.addRow(fila);
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEventoU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JComboBox<String> CboAgregar;
    private javax.swing.JComboBox<String> CboEliminar;
    private javax.swing.JTable TblMenu;
    private javax.swing.JLabel TxtEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
