/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Conexiones.Procedimientos;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Finanzas_CDMX
 */
public class ModificarPerfil extends javax.swing.JFrame {

    String CONTRASEÑA, ID, CORREO_E, CELULAR, TELEFONO;
    
    public ModificarPerfil() {
        initComponents();
        ID=Clases.Logueo.IDUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnVolver = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        PwsContraseña = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        TxteCelular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxteTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxteEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnVolver.setText("Volver");
        BtnVolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 80, -1));

        BtnModificar.setText("Modificar");
        BtnModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 90, -1));

        PwsContraseña.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PwsContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PwsContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(PwsContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 250, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Slab Medium", 0, 24)); // NOI18N
        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        TxteCelular.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(TxteCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 247, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Slab Medium", 0, 24)); // NOI18N
        jLabel4.setText("Celular:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        TxteTelefono.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(TxteTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 247, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 24)); // NOI18N
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        TxteEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(TxteEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 247, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Slab Medium", 0, 24)); // NOI18N
        jLabel2.setText("E-Mail:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        jLabel1.setText("MODIFICAR PERFIL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondog.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        CONTRASEÑA=PwsContraseña.getText();
        if(CONTRASEÑA=="")
            CONTRASEÑA=null;
        CORREO_E=TxteEmail.getText();
        if(CORREO_E=="")
            CORREO_E=null;
        CELULAR=TxteCelular.getText();
        if(CELULAR=="")
            CELULAR=null;
        TELEFONO=TxteTelefono.getText();
        if(TELEFONO=="")
            TELEFONO=null;
        
        try{
            Procedimientos.CAMB_USU(ID, CORREO_E, CELULAR, TELEFONO, CONTRASEÑA);
            PwsContraseña.setText("");
            TxteEmail.setText("");
            TxteCelular.setText("");
            TxteTelefono.setText("");
            
            JOptionPane.showMessageDialog(null, "Cambios Realizados Correctamente");
        }catch(SQLException e){
            
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        BienvenidaU BU = new BienvenidaU();
        BU.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void PwsContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PwsContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PwsContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JPasswordField PwsContraseña;
    private javax.swing.JTextField TxteCelular;
    private javax.swing.JTextField TxteEmail;
    private javax.swing.JTextField TxteTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
