/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Conexiones.Conexion;
import Conexiones.Procedimientos;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ModificarDetallesEventoU extends javax.swing.JFrame {

    
    String ID, playlist, SMANTEL, SMONTAJE, MANTEL, MONTAJE;
    
    public ModificarDetallesEventoU() {
        initComponents();
        
        ID = Clases.EventosUsuario.IDEvento;
        TxtEvento.setText(ID);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnModificar = new javax.swing.JButton();
        CboMontaje = new javax.swing.JComboBox<>();
        CboManteleria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtePlaylist = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtEvento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnModificar.setText("Modificar");
        BtnModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 90, -1));

        CboMontaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Escuela", "Auditorio", "Espiga", "Herradura", "Media Luna", "Imperial", "Mesa Rusa", "Banquete", "Cocktel" }));
        CboMontaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboMontajeActionPerformed(evt);
            }
        });
        getContentPane().add(CboMontaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        CboManteleria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Satín", "Organza", "Plastico", "Razo" }));
        CboManteleria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboManteleriaActionPerformed(evt);
            }
        });
        getContentPane().add(CboManteleria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel4.setText("Mantelería:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel5.setText("Montaje:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));
        getContentPane().add(TxtePlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 350, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 16)); // NOI18N
        jLabel3.setText("Playlist:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 0, 20)); // NOI18N
        jLabel2.setText("Para el evento: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        TxtEvento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(TxtEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 170, 30));

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        jLabel1.setText("MODIFICAR DETALLES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondog.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 700, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboManteleriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboManteleriaActionPerformed
        SMANTEL=CboManteleria.getSelectedItem().toString();
    }//GEN-LAST:event_CboManteleriaActionPerformed

    private void CboMontajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboMontajeActionPerformed
        SMONTAJE=CboMontaje.getSelectedItem().toString();
    }//GEN-LAST:event_CboMontajeActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        switch(SMANTEL){
            case "Seleccionar":
                MANTEL="";
                break;
            case "Satín":
                MANTEL="0001";
                break;
            case "Organza":
                MANTEL="0003";
                break;
            case "Plastico":
                MANTEL="0004";
                break;
            case "Razo":
                MANTEL="0013";
                break;
        }
        if(MANTEL==""){
            MANTEL=null;
        }
        
        switch(SMONTAJE){
            case "Seleccionar":
                MONTAJE="";
                break;
            case "Escuela":
                MONTAJE="001";
                break;
            case "Auditorio":
                MONTAJE="003";
                break;
            case "Espiga":
                MONTAJE="005";
                break;
            case "Herradura":
                MONTAJE="004";
                break;
            case "Media Luna":
                MONTAJE="007";
                break;
            case "Imperial":
                MONTAJE="008";
                break;
            case "Mesa Rusa":
                MONTAJE="006";
                break;
            case "Banquete":
                MONTAJE="009";
                break;
            case "Cocktel":
                MONTAJE="002";
                break;
        }
        if(MONTAJE==""){
            MONTAJE=null;
        }
        
        playlist=TxtePlaylist.getText();
        if(playlist==""){
            playlist=null;
        }
        try{
            Procedimientos.CAMB_EVENTO(ID, playlist, MANTEL, MONTAJE);
        }catch(SQLException e){
            
        }
        
        
        EventosUsuario EU = new EventosUsuario();
        EU.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BtnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDetallesEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDetallesEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDetallesEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDetallesEventoU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDetallesEventoU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModificar;
    private javax.swing.JComboBox<String> CboManteleria;
    private javax.swing.JComboBox<String> CboMontaje;
    private javax.swing.JLabel TxtEvento;
    private javax.swing.JTextField TxtePlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
